#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — provisioning the release environment (issue #48).
#
# Nothing here is a repo secret. The two sensitive values -- the login keychain
# password and the runner registration token -- are read into a shell variable,
# used once, and never written to disk or to GitHub. ENV_FILE therefore lives
# outside the repo and holds only the three harmless identifiers, so a stray
# file can never be committed.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ENV_FILE:-$HOME/.config/libretexts-reader/release-setup.env}"
mkdir -p "$(dirname "$ENV_FILE")"

REPO="johnnylibretexts/libretexts-reader"
EXPECTED_GH_ACCOUNT="johnnylibretexts"
RUNNER_DIR="$HOME/actions-runner"

TOTAL_STAGES=7
TOTAL_MINUTES=30

banner "LibreTexts Reader — release environment setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — tools and the right GitHub account" 2
say "Checking the things every later stage depends on. Nothing is changed here."
printf '\n'

preflight_failed=0
_check() { # _check "label" "command..."
  if eval "$2" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
    preflight_failed=1
  fi
}

_check "xcrun (Xcode command line tools)"  "command -v xcrun"
_check "security (keychain CLI)"           "command -v security"
_check "gh (GitHub CLI)"                   "command -v gh"
_check "gh is authenticated"               "gh auth status"
_check "in the libretexts-reader repo"     "test -f src-tauri/tauri.conf.json"

# This machine holds credentials for two GitHub accounts. `gh variable set`
# writes to whichever is active, so the wrong one puts APPLE_SIGNING_IDENTITY
# on a repo the workflow never reads -- and the failure only shows up much
# later, as an empty variable at release.yml:76.
active_account="$(gh api user --jq .login 2>/dev/null || echo unknown)"
if [[ "$active_account" == "$EXPECTED_GH_ACCOUNT" ]]; then
  printf '  %s✓%s gh active account is %s\n' "$GREEN" "$RESET" "$active_account"
else
  printf '  %s✗%s gh active account is %s, expected %s\n' \
    "$RED" "$RESET" "$active_account" "$EXPECTED_GH_ACCOUNT"
  note "     fix with: gh auth switch --user $EXPECTED_GH_ACCOUNT"
  preflight_failed=1
fi

if (( preflight_failed )); then
  printf '\n'
  warn "Fix the ✗ items above, then re-run this wizard."
  exit 1
fi
printf '\n'
pause "All good. Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Install your Developer ID Application certificate" 5
say "The whole pipeline is gated on this certificate. Everything else here"
say "assumes it is in your login keychain."
printf '\n'

_find_identity() {
  security find-identity -v -p codesigning 2>/dev/null \
    | grep 'Developer ID Application' | head -1 \
    | sed -E 's/.*"(.*)".*/\1/'
}

APPLE_SIGNING_IDENTITY="$(_find_identity || true)"
if [[ -n "$APPLE_SIGNING_IDENTITY" ]]; then
  printf '  %s✓%s already installed: %s\n' "$GREEN" "$RESET" "$APPLE_SIGNING_IDENTITY"
else
  warn "No Developer ID Application certificate found in the login keychain."
  printf '\n'
  step "Find your certificate export (a .p12 file) from the Mac that has it."
  step "Double-click it. Keychain Access will ask for the .p12 password."
  step "Make sure it lands in the 'login' keychain, not 'System'."
  note  "No .p12 to hand? Create a fresh certificate instead:"
  note  "  Keychain Access → Certificate Assistant → Request a Certificate"
  note  "  from a Certificate Authority (save to disk), then upload that CSR at"
  note  "  https://developer.apple.com/account/resources/certificates/add"
  note  "  choosing 'Developer ID Application', and double-click the download."
  printf '\n'
  while [[ -z "$APPLE_SIGNING_IDENTITY" ]]; do
    pause "Press Enter once the certificate is installed…"
    APPLE_SIGNING_IDENTITY="$(_find_identity || true)"
    [[ -z "$APPLE_SIGNING_IDENTITY" ]] && warn "Still not visible to codesign. Check it is in the 'login' keychain."
  done
  printf '  %s✓%s found: %s\n' "$GREEN" "$RESET" "$APPLE_SIGNING_IDENTITY"
fi

# "Developer ID Application: Some Name (TEAMID)" -> TEAMID, to prefill stage 4.
APPLE_TEAM_ID_GUESS="$(printf '%s' "$APPLE_SIGNING_IDENTITY" | sed -E 's/.*\(([A-Z0-9]+)\)$/\1/')"
write_env APPLE_SIGNING_IDENTITY "$APPLE_SIGNING_IDENTITY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Authorize codesign to use the key without a prompt" 2
say "By default macOS shows a GUI 'allow access to your key?' dialog the first"
say "time codesign uses this certificate. A headless runner cannot click it, so"
say "the release job would hang for its full 60-minute timeout with no error."
printf '\n'
note "This grants apple-tool: and apple: access to your login keychain items."
note "Your password is used for this one command and is never stored or sent."
printf '\n'

if confirm "Run set-key-partition-list on the login keychain now?"; then
  ask_secret LOGIN_KEYCHAIN_PW "macOS login password:"
  if security set-key-partition-list -S apple-tool:,apple: -s \
       -k "$LOGIN_KEYCHAIN_PW" login.keychain-db >/dev/null 2>&1; then
    printf '  %s✓%s codesign can now use the key non-interactively\n' "$GREEN" "$RESET"
  else
    warn "That did not succeed — usually a wrong password."
    SKIPPED+=("security set-key-partition-list (re-run this wizard)")
  fi
  # Out of memory the moment it is done with.
  unset LOGIN_KEYCHAIN_PW
else
  SKIPPED+=("security set-key-partition-list — the runner may hang on a keychain prompt")
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Store notarization credentials as the 'jr-notary' profile" 5
say "RELEASE.md and release.yml both call --keychain-profile jr-notary. Storing"
say "it in the keychain keeps your Apple password out of the shell and the logs."
printf '\n'

if xcrun notarytool history --keychain-profile jr-notary >/dev/null 2>&1; then
  printf '  %s✓%s the jr-notary profile already works\n' "$GREEN" "$RESET"
else
  step "You need an app-specific password (not your Apple ID password)."
  open_url "https://appleid.apple.com/account/manage"
  step "Sign in → App-Specific Passwords → generate one, and copy it."
  printf '\n'
  ask APPLE_ID "Apple ID email:"
  [[ -n "$APPLE_TEAM_ID_GUESS" ]] && note "Team ID from your certificate: $APPLE_TEAM_ID_GUESS"
  ask APPLE_TEAM_ID "Team ID:"
  [[ -z "$APPLE_TEAM_ID" ]] && APPLE_TEAM_ID="$APPLE_TEAM_ID_GUESS"
  write_env APPLE_ID "$APPLE_ID"
  write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
  printf '\n'
  say "notarytool will now prompt for the app-specific password itself —"
  say "this wizard never sees or stores it."
  printf '\n'
  if xcrun notarytool store-credentials jr-notary \
       --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID"; then
    printf '  %s✓%s jr-notary stored\n' "$GREEN" "$RESET"
  else
    warn "store-credentials failed."
    SKIPPED+=("xcrun notarytool store-credentials jr-notary")
  fi
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Publish the signing identity as a repo variable" 2
say "release.yml:26 reads vars.APPLE_SIGNING_IDENTITY and release.yml:76 exits 1"
say "when it is empty. It is a certificate name, not a secret — a variable, so"
say "it stays readable in the logs when a build goes wrong."
printf '\n'
set_var APPLE_SIGNING_IDENTITY "$APPLE_SIGNING_IDENTITY"

readback="$(gh variable get APPLE_SIGNING_IDENTITY --repo "$REPO" 2>/dev/null || echo '')"
if [[ "$readback" == "$APPLE_SIGNING_IDENTITY" ]]; then
  printf '  %s✓%s read back from GitHub and it matches\n' "$GREEN" "$RESET"
else
  warn "Could not read the variable back — check it in Settings → Secrets and variables → Actions."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Register this Mac as the release runner" 8
say "release.yml pins runs-on: [self-hosted, macos, release]. With no runner"
say "registered, pushing a tag queues a job nothing ever picks up — it waits"
say "until GitHub expires it, with no failure signal at all."
printf '\n'

if gh api "repos/$REPO/actions/runners" --jq '.total_count' 2>/dev/null | grep -qv '^0$'; then
  printf '  %s✓%s a runner is already registered\n' "$GREEN" "$RESET"
elif [[ -d "$RUNNER_DIR" ]]; then
  printf '  %s✓%s runner already downloaded at %s\n' "$GREEN" "$RESET" "$RUNNER_DIR"
  note "If it is not registered, run ./config.sh in that directory."
else
  say "Fetching the current runner release…"
  RUNNER_VER="$(gh api repos/actions/runner/releases/latest --jq '.tag_name' 2>/dev/null | sed 's/^v//')"
  if [[ -z "$RUNNER_VER" ]]; then
    warn "Could not determine the latest runner version."
    SKIPPED+=("self-hosted runner registration")
  else
    note "runner $RUNNER_VER → $RUNNER_DIR"
    open_url "https://github.com/$REPO/settings/actions/runners/new?arch=arm64&os=osx"
    step "On that page, copy the token shown in the ./config.sh --token line."
    ask_secret RUNNER_TOKEN "Paste the registration token:"

    if [[ -n "$RUNNER_TOKEN" ]]; then
      mkdir -p "$RUNNER_DIR"
      ( cd "$RUNNER_DIR" \
        && curl -fsSL -o runner.tar.gz \
             "https://github.com/actions/runner/releases/download/v${RUNNER_VER}/actions-runner-osx-arm64-${RUNNER_VER}.tar.gz" \
        && tar xzf runner.tar.gz && rm -f runner.tar.gz ) \
        && ( cd "$RUNNER_DIR" && ./config.sh \
               --url "https://github.com/$REPO" \
               --token "$RUNNER_TOKEN" \
               --labels macos,release \
               --name jr-release-mac \
               --ephemeral --unattended ) \
        && printf '  %s✓%s runner registered\n' "$GREEN" "$RESET" \
        || { warn "Runner setup did not complete."; SKIPPED+=("self-hosted runner registration"); }
      # Short-lived, and no reason to keep it a moment longer.
      unset RUNNER_TOKEN
    fi
  fi
fi

printf '\n'
warn "The runner is --ephemeral: it takes ONE job and exits."
say "Open a second terminal now and leave this running:"
note "  cd $RUNNER_DIR && ./run.sh"
printf '\n'
pause "Press Enter once ./run.sh is listening…"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Rehearse it — dry run, no notarizing, no publishing" 6
say "dry_run builds and Developer-ID-signs, then stops. It proves the eight"
say "steps before publishing without creating a release or spending a"
say "notarization round trip. This pipeline has never run once."
printf '\n'

if confirm "Trigger the Release workflow with dry_run: true?"; then
  if gh workflow run release.yml --repo "$REPO" -f dry_run=true; then
    printf '  %s✓%s dispatched\n' "$GREEN" "$RESET"
    say "Watching it — this takes a few minutes."
    sleep 10
    run_id="$(gh run list --repo "$REPO" --workflow=release.yml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || echo '')"
    if [[ -n "$run_id" ]]; then
      gh run watch "$run_id" --repo "$REPO" --exit-status \
        && printf '\n  %s✓ dry run passed — the release path works end to end%s\n' "$GREEN" "$RESET" \
        || { warn "The dry run failed. Read the log:"; note "  gh run view $run_id --repo $REPO --log-failed"; }
    else
      note "Watch it at https://github.com/$REPO/actions"
    fi
  else
    warn "Could not dispatch the workflow."
    SKIPPED+=("dry-run workflow_dispatch")
  fi
else
  SKIPPED+=("dry-run workflow_dispatch — do this before pushing any real tag")
fi

finish
printf '  %sNext:%s once the dry run is green, cut the beta:\n' "$BOLD" "$RESET"
note "  cd $RUNNER_DIR && ./run.sh     # ephemeral: start it again per release"
note "  git tag v0.1.0-beta.1 && git push origin v0.1.0-beta.1"
printf '\n'
